pipeline {
agent any

```
environment {
    SERVICE_NAME = 'auth-service'
    IMAGE_TAG = "1.0.${BUILD_NUMBER}"
}

tools {
    maven 'maven-3.9'
    jdk 'jdk21'
}

stages {

    stage('Checkout') {
        steps {
            checkout scm
        }
    }

    stage('Compile') {
        steps {
            dir("${SERVICE_NAME}") {
                sh 'mvn clean compile -B'
            }
        }
    }

    stage('Unit Test') {
        steps {
            dir("${SERVICE_NAME}") {
                sh 'mvn test -B'
            }
        }
        post {
            always {
                junit allowEmptyResults: true,
                      testResults: '**/target/surefire-reports/*.xml'
            }
        }
    }

    stage('SonarQube Scan') {
        steps {
            dir("${SERVICE_NAME}") {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar -Dsonar.projectKey=securebank-auth -B'
                }
            }
        }
    }

    stage('Package') {
        steps {
            dir("${SERVICE_NAME}") {
                sh 'mvn package -DskipTests -B'
            }
        }
    }
}

post {
    success {
        echo 'Build Successful'
    }

    failure {
        echo 'Build Failed'
    }

    always {
        cleanWs()
    }
}
```

}
